version: '3'
services:
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome-debug:3.141.59-20210929
    ports:
      - 4444:4444
      - 5901:5900
    shm_size: "2gb"
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/opt/app
    tty: true